import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'The Midnight Essential',
    description: 'A timeless black tee crafted from premium organic cotton. Minimalist design for maximum impact.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80',
    category: 'Essentials',
    featured: true,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '2',
    name: 'Lunar Eclipse Graphic',
    description: 'Abstract lunar phases printed with eco-friendly ink. A subtle nod to the celestial.',
    price: 55,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
    category: 'Graphics',
    featured: true,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: '3',
    name: 'Slate Grey Oversize',
    description: 'Relaxed fit with a heavy-weight feel. Perfect for layering or a bold standalone look.',
    price: 50,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80',
    category: 'Essentials',
    featured: true,
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: '4',
    name: 'Architectural Line Art',
    description: 'Clean lines inspired by modernist architecture. Sophistication in every stitch.',
    price: 60,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    category: 'Graphics',
    featured: true,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '5',
    name: 'Deep Forest Pocket Tee',
    description: 'Subtle forest green with a functional pocket. Nature-inspired, city-ready.',
    price: 48,
    image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=800&q=80',
    category: 'Essentials',
    featured: false,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: '6',
    name: 'Crimson Wave',
    description: 'Bold red statement tee with an abstract wave design. Perfect for making an impression.',
    price: 52,
    image: 'https://images.unsplash.com/photo-1556821552-9f6db051193a?auto=format&fit=crop&w=800&q=80',
    category: 'Graphics',
    featured: true,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '7',
    name: 'Cream Minimalist',
    description: 'Soft cream-colored basic tee. Versatile staple for any wardrobe. Pure simplicity.',
    price: 42,
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
    category: 'Essentials',
    featured: false,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '8',
    name: 'Geometric Sunset',
    description: 'Vibrant geometric patterns inspired by desert sunsets. Bold and eye-catching.',
    price: 58,
    image: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1991?auto=format&fit=crop&w=800&q=80',
    category: 'Graphics',
    featured: true,
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: '9',
    name: 'Sage Canvas',
    description: 'Muted sage green heavyweight tee. Comfortable and contemporary for everyday wear.',
    price: 49,
    image: 'https://images.unsplash.com/photo-1618611707367-41e6b7735abc?auto=format&fit=crop&w=800&q=80',
    category: 'Essentials',
    featured: false,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '10',
    name: 'Retro Typography',
    description: 'Vintage-inspired typography print. Nostalgic vibes with a modern twist.',
    price: 56,
    image: 'https://images.unsplash.com/photo-1505033575518-a36ea2ef75c2?auto=format&fit=crop&w=800&q=80',
    category: 'Graphics',
    featured: true,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: '11',
    name: 'Cool Yellow boat',
    description: 'Vibrant yellow tee with a nautical boat design. Perfect for summer style and adventure.',
    price: 51,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80',
    category: 'Graphics',
    featured: false,
    sizes: ['S', 'M', 'L', 'XL'],
  },
];
